//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIP
{
    namespace Project_Mouse
    {
        namespace ENUM
        {
            public enum GroupType
            {
                /// <summary>
                /// 家具套装
                /// </summary>
                FurnitureSuit = 1,
                /// <summary>
                /// 服装套装
                /// </summary>
                ClothSuit = 2,
            }
        }
    }
}
