
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace CLIP
{
    namespace Project_Mouse
    {
        namespace ENUM
        {
            public enum Item_Type
            {
                /// <summary>
                /// 食物
                /// </summary>
                Food = 1,
                /// <summary>
                /// 磁带
                /// </summary>
                Tape = 2,
                /// <summary>
                /// 零食
                /// </summary>
                Snack = 3,
                /// <summary>
                /// 花盆
                /// </summary>
                Pot = 4,
                /// <summary>
                /// 种子
                /// </summary>
                Seed = 5,
                /// <summary>
                /// 收获物
                /// </summary>
                Harvest = 6,
                /// <summary>
                /// 食材
                /// </summary>
                Food_Material = 7,
                /// <summary>
                /// 其他素材
                /// </summary>
                Other_Material = 8,
                /// <summary>
                /// 肥料
                /// </summary>
                Fertilizer = 9,
                /// <summary>
                /// 房间放置物
                /// </summary>
                Room_Placement = 10,
                /// <summary>
                /// 货币
                /// </summary>
                Currency = 11,
                /// <summary>
                /// 服装
                /// </summary>
                Cloth = 12,
            }
        }
    }
}

