//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CLIP
{
    namespace Project_Mouse
    {
        namespace ENUM
        {
               [System.Serializable]
            public enum Mood_Tag
            {
                /// <summary>
                /// 悠闲
                /// </summary>
                Leisure = 1,
                /// <summary>
                /// 轻松
                /// </summary>
                Relax = 2,
                /// <summary>
                /// 平静
                /// </summary>
                Calm = 3,
                /// <summary>
                /// 活力
                /// </summary>
                Happy = 4,
                /// <summary>
                /// 都市
                /// </summary>
                City = 5,
                /// <summary>
                /// 中国风
                /// </summary>
                Chinese=6,
                /// <summary>
                /// 自然
                /// </summary>
                Natural = 7,
                /// <summary>
                /// 安静
                /// </summary>
                Slient = 8,


            }
        }
    }
}