
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CLIP.Project_Mouse.ENUM;
using Newtonsoft.Json;




namespace CLIP
{
    namespace Project_Mouse
    {
        namespace Kernel
        {

            [System.Serializable]
            public class cloth_info
            {
                /// <summary>
                /// 物品Id
                /// </summary>
                public int cloth_id;
                /// <summary>
                /// 名称
                /// </summary>
                public string cloth_name;
                /// <summary>
                /// 描述
                /// </summary>
                public string desc;
                /// <summary>
                /// 一级分类
                /// </summary>
                public Cloth_First_Category first_category;
                /// <summary>
                /// 二级分类
                /// </summary>
                public Cloth_Second_Category second_category;
                /// <summary>
                /// 占用槽位
                /// </summary>
                public System.Collections.Generic.List<string> slots_occupied;
                /// <summary>
                /// 品级(普通,中级,高级)
                /// </summary>
                public string rarity;
                /// <summary>
                /// 引擎内资源路径
                /// </summary>
                public string res_path;
                /// <summary>
                /// 服装款式名
                /// </summary>
                public string parent_cloth_name;
                /// <summary>
                /// 服装颜色
                /// </summary>
                public string cloth_color;

                public override string ToString()
                {
                    return "{ "
                    + "cloth_id:" + cloth_id + ","
                    + "cloth_name:" + cloth_name + ","
                    + "desc:" + desc + ","
                    + "first_Category:" + first_category + ","
                    + "second_category:" + second_category + ","
                    + "slots_occupied:" + JsonConvert.SerializeObject(slots_occupied) + ","
                    + "rarity:" + rarity + ","
                    + "res_path:" + res_path + ","
                    + "}";
                }

                public static string cloth_type_cn_to_en(string cn)
                {
                    switch (cn)
                    {
                        case "配饰": return "Attachment";
                        case "上衣": return "Upper";
                        case "裤子": return "Lower";
                        case "鞋袜": return "Buttom";
                        case "裙子": return "Dress";
                        default: return "";
                    }
                }
            }
        }
    }
}
 



