
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using Newtonsoft.Json;



namespace CLIP
{
    namespace Project_Mouse
    {
        namespace Kernel
        {
            namespace Inventory
            {
                [System.Serializable]
                public class item_group
                {
                    /// <summary>
                    /// 物品套装Id
                    /// </summary>
                    public int item_group_id;
                    /// <summary>
                    /// 物品套装名
                    /// </summary>
                    public string item_group_name;
                    /// <summary>
                    /// 描述
                    /// </summary>
                    public string desc;
                    /// <summary>
                    /// 套装类型
                    /// </summary>
                    public string group_type;
                    /// <summary>
                    /// 风格
                    /// </summary>
                    public string style;
                    /// <summary>
                    /// 套装物品列表
                    /// </summary>
                    public List<string> group_item_list;
                    /// <summary>
                    /// 套装颜色
                    /// </summary>
                    public string shop_item_list_color;
                    /// <summary>
                    /// 对应的原色套装
                    /// </summary>
                    public string parent_item_group;

                    public string ToString()
                    {
                        return "{ "
                        + "item_group_id:" + item_group_id + ","
                        + "item_group_name:" + item_group_name + ","
                        + "desc:" + desc + ","
                        + "group_type:" + group_type + ","
                        + "style:" + style + ","
                        + "group_item_list:" + JsonConvert.SerializeObject(group_item_list) + ","
                        + "shop_item_list_color:" + shop_item_list_color + ","
                        + "}";
                    }
                }
            }
        }
    }
}


