
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Collections;
using System.Collections.Generic;



namespace CLIP
{
    namespace Project_Mouse
    {
        namespace Kernel
        {
            namespace Inventory
            {
                [System.Serializable]
                public class shop_list
                {

                    /// <summary>
                    /// 商品列表id
                    /// </summary>
                    public int shop_list_id;
                    /// <summary>
                    /// 商品列表名
                    /// </summary>
                    public string shop_list_name;
                    /// <summary>
                    /// 商品列表类型
                    /// </summary>
                    public string shop_list_type;
                    /// <summary>
                    /// 是否为限定
                    /// </summary>
                    public bool is_limited;
                    /// <summary>
                    /// 单件商品列表
                    /// </summary>
                    public List<shop_item> single_shop_item_list;
                    /// <summary>
                    /// list,string
                    /// </summary>
                    public List<string> group_shop_item_list;

                    public override string ToString()
                    {
                        return "{ "
                        + "shop_list_id:" + shop_list_id + ","
                        + "shop_list_name:" + shop_list_name + ","
                        + "shop_list_type:" + shop_list_type + ","
                        + "is_limited:" + is_limited + ","
                        + "single_shop_item_list:" + JsonConvert.SerializeObject(single_shop_item_list) + ","
                        + "group_shop_item_list:" + JsonConvert.SerializeObject(group_shop_item_list) + ","
                        + "}";
                    }
                }


            }
        }
    }
}