internal class GameEventDefine
{
    public const string CS_RESTART_GAME  = "CS_RESTART_GAME";
    public const string GAME_VERSION_CHECK_START = " GAME_VERSION_CHECK_START";
    public const string GAME_VERSION_CHECK_END = "GAME_VERSION_CHECK_END";
    public const string GAME_VERSION_CHECK_INFO_GET_FAILED = "GAME_VERSION_CHECK_INFO_GET_FAILED";
    public const string GAME_VERSION_CHECK_FILE_PROCESS = "GAME_VERSION_CHECK_FILE_PROCESS";
    public const string GAME_VERSION_DOWNLOAD_FILE_PROCESS = "GAME_VERSION_DOWNLOAD_FILE_PROCESS";
    public const string GAME_VERSION_CHECK_FILE_FAILED = "GAME_VERSION_CHECK_FILE_FAILED";
    public const string GAME_VERSION_CHECK_FILE = "GAME_VERSION_CHECK_FILE";
    public const string GAME_VERSION_BIG_NEED_APPSTORE_DOWNLOAD = "GAME_VERSION_BIG_NEED_APPSTORE_DOWNLOAD";
}