//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CLIP.Project_Mouse.ENUM;
using Newtonsoft.Json;


namespace CLIP
{
    namespace Project_Mouse
    {
        [System.Serializable]
        public class flower_pot_info
        {
            /// <summary>
            /// id
            /// </summary>
            public   int pot_id;
            /// <summary>
            /// 名字
            /// </summary>
            public   string pot_name;
            /// <summary>
            /// 类型
            /// </summary>
            public Plant_First_Category firstCategory;
            public Plant_Second_Category secondCategory;
            /// <summary>
            /// 颜色列表
            /// </summary>
            public   System.Collections.Generic.List<string> color_list;
            /// <summary>
            /// 最大耐久度
            /// </summary>
            public   int max_durability;
            /// <summary>
            /// 长边
            /// </summary>
            public   int long_grid_size;
            /// <summary>
            /// 短边
            /// </summary>
            public   int short_grid_size;
                /// <summary>
                    /// 可容纳作物大小
            /// </summary>
            public  int plant_size;
            /// <summary>
            /// 对应坏花瓶的物品名
            /// </summary>
            public  string broken_pot_name;
            /// <summary>
            /// 对应的原色花瓶
            /// </summary>
            public  string original_color_pot_name;
            /// <summary>
            /// 是否可修复
            /// </summary>
            public  bool can_repair;
            /// <summary>
            /// 场景内资源路径
            /// </summary>
            public  string res_url;

            /// <summary>
            /// 获取方式
            /// </summary>
            public   string obtain_source;
            /// <summary>
            /// 颜色
            /// </summary>
            public   string color;
            /// <summary>
            /// 详细颜色
            /// </summary>
            public string detail_color;
            public override string ToString()
                {
                    return "{ "
                    + "pot_id:" + pot_id + ","
                    + "pot_name:" + pot_name + ","
                    + "color_list:" + color_list.ToString() + ","
                    + "max_durability:" + max_durability + ","
                    + "long:" + long_grid_size + ","
                    + "width:" + short_grid_size + ","
                    + "plant_size:" + plant_size + ","
                    + "broken_pot_name:" + broken_pot_name + ","
                    + "original_color_pot_name:" + original_color_pot_name + ","
                    + "can_repair:" + can_repair + ","
                    + "res_url:" + res_url + ","
                        + "obtain_source:" + obtain_source + ","
                    + "color:" + color + ","
                        + "detail_color:" + detail_color + ","
                    + "}";
                }
            }
        
    }
}