//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using CLIP.Project_Mouse.ENUM;


namespace CLIP
{
    namespace Project_Mouse
    {
           [System.Serializable]
        public class Plant_Info
        {
            /// <summary>
            /// id
            /// </summary>
            public int plant_id;
            /// <summary>
            /// 名字
            /// </summary>
            public string plant_name;
            /// <summary>
            /// 类型
            /// </summary>
            public Plant_First_Category first_category;
            public Plant_Second_Category second_category;

            /// <summary>
            /// 植物尺寸
            /// </summary>
            public int Plant_size;

   /// <summary>
    /// 植物描述
    /// </summary>
    public  string plant_Describe;
    
    /// <summary>
    /// 阶段时间，分钟
    /// </summary>
    public  System.Collections.Generic.List<int> life_cycle_table;
    /// <summary>
    /// 可收获次数（-1是永久值）
    /// </summary>
    public  int harvest_time;
    /// <summary>
    /// 收获后进入阶段
    /// </summary>
    public  int return_stage_info;
            /// <summary>
            /// 未浇水减速倍率
            /// </summary>
            public float no_water_slow_ratio;
            /// <summary>
            /// 一次浇水有效时间（分钟）
            /// </summary>
            public int irrigation_effective_time;
            /// <summary>
            /// 种子名字
            /// </summary>
            public string seed_name;
            /// <summary>
            /// 产出物名字
            /// </summary>
            public string harvested_item_name;
            /// <summary>
            /// 最小个数
            /// </summary>
            public int min_harvest_count;
            /// <summary>
            /// 最大个数
            /// </summary>
            public int max_harvest_count;

            /// <summary>
            /// 是否有隐藏款植物
            /// </summary>
            public   bool have_hided;
            /// <summary>
            /// 隐藏变种名
            /// </summary>
            public  string hided_variant_name;
    /// <summary>
    /// 隐藏变种出现概率
    /// </summary>
    public  float hided_variant_rate;
            /// <summary>
            /// 场景内资源路径
            /// </summary>
            public string res_url;
            /// <summary>
            /// 种子获取方式
            /// </summary>
            public string seed_source;
            /// <summary>
            /// 成熟物类型
            /// </summary>
            public string harvest_type;

            public override string ToString()
            {
              return "{ "
        + "plant_id:" + plant_id + ","
        + "plant_name:" + plant_name + ","
        + "plant_Type:" + second_category + ","
        + "Plant_size:" + Plant_size + ","
        + "plant_Describe:" + plant_Describe + ","
        + "life_cycle_table:" + life_cycle_table.ToString() + ","
        + "harvest_time:" + harvest_time + ","
        + "return_stage_info:" + return_stage_info + ","
        + "no_water_slow_ratio:" + no_water_slow_ratio + ","
        + "seed_name:" + seed_name + ","
        + "harvested_item_name:" + harvested_item_name + ","
        + "min_harvest_count:" + min_harvest_count + ","
        + "max_harvest_count:" + max_harvest_count + ","
        + "is_hided:" + have_hided + ","
        + "hided_variant_name:" + hided_variant_name + ","
        + "hided_variant_rate:" + hided_variant_rate + ","
         + "seed_source:" + seed_source + ","
        + "harvest_type:" + harvest_type + ","
         + "res_url:" + res_url + ","
        + "}";
             
            }
        }
    }
}