
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;



namespace CLIP
{
    namespace Project_Mouse
    {
        namespace Kernel
        {
            [System.Serializable]

            public class global_const
            {

                /// <summary>
                /// id
                /// </summary>
                public int id;
                /// <summary>
                /// 下雨概率
                /// </summary>
                public float rain_p;
                /// <summary>
                /// 下雨最小时长
                /// </summary>
                public int rain_len_min;
                /// <summary>
                /// 下雨最大时长
                /// </summary>
                public int rain_len_max;



                public override string ToString()
                {
                    return "{ "
                    + "id:" + id + ","
                    + "rain_p:" + rain_p + ","
                    + "rain_len_min:" + rain_len_min + ","
                    + "rain_len_max:" + rain_len_max + ","
                    + "}";
                }
            }
        }
    }
}
