syntax = "proto3";

package cmd;

option go_package = "github.com/xcompany/xgame/proto/cmd";

import "common/common.proto";

//SEQ[5001,9999]
//获取玩家信息(可跨服)请求
message GetRoleInfoReq {//module=logic
  int32 ServerID = 1; //服务器ID
  string RoleID = 2;  //角色ID
}

//获取玩家信息(可跨服)响应
message GetRoleInfoRes {
  common.ServerRoleInfo RoleInfo = 1;
}

//聊天发送请求
message ChatSendReq {
  common.ChatChannelType ChannelType = 1; //聊天频道类型
  uint64 ReceiveID = 2;                   //频道ID
  common.ChatMsgType MsgType = 3;         //信息类型
  string Text = 4;                        //文本内容
  uint64 SpecialUID = 5;                  //分享目标uid
  common.SimpleRoleInfo Sender = 6;       //发送角色信息(前端不用)
  common.SimpleRoleInfo Receiver = 7;     //接收角色信息(前端只要设置一个serverID)
  uint64 ChannelUid = 10; //频道UID
  int32 MsgArea = 11; //消息推送范围 -10：仅推送给发送人
  common.GameServer SenderServerInfo= 12;//发送者服务器信息
}

//聊天发送响应
message ChatSendRes {
}

//登录后同步聊天频道信息给到玩家
message SyncChatChannelInfoS2C {
  repeated common.GroupChatChannel GroupChatChannels = 1;         //群聊频道
  repeated common.PrivateChatChannel PrivateChatChannels = 2;     //私聊频道
}

//聊天消息推送
message SyncChatChannelMsgS2C {
  common.ChatChannelType ChannelType = 1; //频道类型
  uint64 ChannelTypeID = 2;               //频道类型ID
  uint64 ChannelUID = 3;                  //频道UID
  repeated common.ChatMessage Content = 4;         //内容
  int32 IsNew = 5;                        //是否是新消息 0 不是 1 是
  int32 IsNewChannel = 6;                 //是否新频道 0 不是 1 是
  common.Spokesman He = 7;                //私聊对象信息
}

//开启/关闭频道推送
message OpenOrCloseChatChannelS2C {
  int32 OpType = 1;                               //操作类型 1 开启 2 解散
  int32 ChannelType = 2;                          //操作类型 1 团组频道 2 私人频道
  common.GroupChatChannel Channel = 3;            //团组频道信息
  common.PrivateChatChannel PrivateChannel = 4;   //私人频道
}

//向前查询聊天记录历史
message QueryChatHistoryReq {
  common.ChatChannelType ChannelType = 1; //聊天频道类型
  uint64 ReceiveID = 2;                   //频道ID
  uint64 TopMsgID = 3;                    //顶部消息ID
  common.SimpleRoleInfo Role = 4;         //角色信息(前端不用)
}

message QueryChatHistoryRes {
  common.ChatChannelType ChannelType = 1; //聊天频道类型
  uint64 ReceiveID = 2;                   //频道ID
  repeated common.ChatMessage Msgs = 3;
  common.Spokesman He = 4;                //私聊更新的角色信息
}

//读取私聊频道信息请求
message ReadPrivateChatReq {
  uint64 HeID = 1; //私聊频道的人员ID
  uint64 ReadMsgID = 2; //已读取到的消息ID
  uint64 RoleID = 3; //读消息的角色ID(前端不用)
  int32 ServerID = 4; //发送者服务器ID(前端不用)
}

//读取私聊频道信息响应
message ReadPrivateChatRes {
}

//跑马灯推送
message MarqueeS2C {
  repeated common.MarqueeInfo Add = 1;//新增/更新的跑马灯
  repeated uint64 Del = 2;//删除/停止的跑马灯
}

//新功能开放通知推送
message NotifyNewFunctionOpenS2C {
  repeated ModuleInfo OpenModules = 1; //开放的模块ID
  repeated ModuleInfo PopModules = 2; //拍脸的模块ID
}

//新功能开放通知推送
message ModuleInfo {
  int32 ModuleType = 1; //模块类型
  int64 ModuleID = 2; //模块配置ID
  uint64 ModuleUID = 3; //模块唯一UID
}
